// src/components/AttributeViewPanelNative.svelte
<script lang="ts">
    import {LoggerService} from "@/services/LoggerService";
    import {getContext} from "svelte";
    import {Context} from "@/types/context";
    import {onMount, onDestroy} from "svelte";
    import {type AttributeView} from "@/types/AttributeView";
    import LayoutTabBar from "@/components/ui/LayoutTabBar.svelte";
    import {settingsStore} from "@/stores/localSettingStore";
    import {AttributeViewService} from "@/services/AttributeViewService";
    import {configStore} from "@/stores/configStore";
    import {documentSettingsStore} from "@/stores/documentSettingsStore";

    interface Props {
        avData: AttributeView[];
    }

    let {avData}: Props = $props();

    let element: HTMLDivElement | null = $state(null);

    // State
    const blockId = getContext(Context.BlockID);
    const protyle = getContext(Context.Protyle);
    const logger = new LoggerService("AttributeViewPanelNative");

    const tabs = $derived(
        avData.map((attributeView) => ({
            key: attributeView.avID,
            name: attributeView.avName,
            icon: "iconDatabase",
        }))
    );

    // Get settings from stores
    const globalShowEmptyAttributes = $derived($configStore.showEmptyAttributes);
    const globalShowPrimaryKey = $derived($configStore.showPrimaryKey);
    const effectiveShowEmptyAttributesStore = $derived(
        documentSettingsStore.getEffectiveShowEmptyAttributes(
            blockId,
            globalShowEmptyAttributes
        )
    );
    const effectiveShowEmptyAttributes = $derived(
        $effectiveShowEmptyAttributesStore
    );

    // Effect to handle store changes
    $effect(() => {
        if (element) {
            //   logger.debug("Adjusting DOM due to store changes", {
            //     globalShowPrimaryKey,
            //     effectiveShowEmptyAttributes,
            //   });

            AttributeViewService.adjustDOM(
                element,
                blockId,
                avData,
                globalShowPrimaryKey,
                effectiveShowEmptyAttributes
            );
        }
    });

    // Track if initial render is complete
    let isInitialized = false;

    // Cleanup function for the MutationObserver that removes data-rendering attributes
    let cleanupDataRenderingObserver: (() => void) | null = null;

    onMount(() => {
        logger.addBreadcrumb(blockId, "onMount");
        renderProtyleAv();
        // Mark as initialized after a tick to avoid immediate re-render
        setTimeout(() => {
            isInitialized = true;
        }, 100);
    });

    onDestroy(() => {
        // Clean up the MutationObserver when component is destroyed
        if (cleanupDataRenderingObserver) {
            cleanupDataRenderingObserver();
            cleanupDataRenderingObserver = null;
        }
    });

    $effect(() => {
        // Only re-render after initial mount is complete
        if (isInitialized && element) {
            logger.debug("avData changed, re-rendering native panel");
            renderProtyleAv();
        }
    });

    const showContent = (tabFocus: string) => {
        if (!tabFocus) {
            return;
        }

        activateTab(tabFocus);
    };

    const activateTab = (tabFocus: string) => {
        logger.addBreadcrumb(blockId, "activateTab: " + LoggerService.getReadableName(tabFocus));
        const targetTab = element.querySelectorAll(
            `[data-type="NodeAttributeView"][data-av-id="${tabFocus}"]`
        );
        const remainingTabs = element.querySelectorAll(
            `[data-type="NodeAttributeView"]:not([data-av-id="${tabFocus}"])`
        );
        if (!targetTab.length) {
            logger.info("showContent: No target tab found");
            return;
        }
        settingsStore.activateTab(blockId, tabFocus);

        targetTab.forEach((item: HTMLElement) => {
            item.classList.remove("dpp-av-panel--hidden");
        });
        remainingTabs.forEach((item: HTMLElement) => {
            item.classList.add("dpp-av-panel--hidden");
        });
    };

    const renderProtyleAv = () => {
        // Clean up previous observer before re-rendering
        if (cleanupDataRenderingObserver) {
            cleanupDataRenderingObserver();
            cleanupDataRenderingObserver = null;
        }

        protyle.renderAVAttribute(element, blockId, (renderedElement) => {
            logger.debug('renderAVAttribute callback called');
            AttributeViewService.adjustDOM(
                renderedElement,
                blockId,
                avData,
                globalShowPrimaryKey,
                effectiveShowEmptyAttributes
            );

            AttributeViewService.removeAvRowClasses(renderedElement);

            if (!settingsStore.isAnyTabActive(blockId)) {
                const first = renderedElement.querySelector(`[data-type="NodeAttributeView"]`);
                activateTab(first.getAttribute("data-av-id"));
            } else {
                activateTab(settingsStore.getActiveTab(blockId));
            }

            // Remove any existing data-rendering attributes immediately
            AttributeViewService.removeDataRenderingFromNodeAttributeViews(renderedElement);

            // Set up MutationObserver to automatically remove data-rendering whenever SiYuan adds it
            cleanupDataRenderingObserver = AttributeViewService.watchAndRemoveDataRendering(renderedElement);
        });
    };

    let currentSettings = $derived($settingsStore.get(blockId));
</script>

<div>
    {#if tabs.length > 1}
        <LayoutTabBar
                {tabs}
                focus={currentSettings.lastSelectedAttributeView}
                onclick={showContent}
        />
    {/if}
    <div class="dpp-av-panel custom-attr dpp-av-panel--native" bind:this={element}></div>
</div>

// src/components/AttributeViewPanelNative.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted } from "vue";
import { LoggerService } from "@/services/LoggerService";
import type { AttributeView } from "@/types/AttributeView";
import LayoutTabBar from "@/components/ui/LayoutTabBar.vue";
import { useLocalSettingStore } from "@/stores/localSettingStore";
import { AttributeViewService } from "@/services/AttributeViewService";
import { useConfigStore } from "@/stores/configStore";
import { useDocumentSettingsStore } from "@/stores/documentSettingsStore";
import { usePluginContext } from "@/composables/usePluginContext";

const props = defineProps<{
  avData: AttributeView[];
  onrefresh?: () => void;
}>();

const element = ref<HTMLDivElement | null>(null);

const { blockId, protyle } = usePluginContext();
const logger = new LoggerService("AttributeViewPanelNative");
const settingsStore = useLocalSettingStore();
const configStore = useConfigStore();
const documentSettingsStore = useDocumentSettingsStore();

const tabs = computed(() => AttributeViewService.buildTabs(props.avData));

const globalShowEmptyAttributes = computed(() => configStore.showEmptyAttributes);
const globalShowPrimaryKey = computed(() => configStore.showPrimaryKey);
const alignPropertiesLeft = computed(() => configStore.alignPropertiesLeft);
const effectiveShowEmptyAttributes = computed(() =>
  documentSettingsStore.getEffectiveShowEmptyAttributes(blockId, globalShowEmptyAttributes.value)
);

const currentSettings = computed(() => settingsStore.getDocumentSettings(blockId));

let isInitialized = false;
let cleanupDataRenderingObserver: (() => void) | null = null;

function isColumnVisible(avId: string, colId: string): boolean {
  return configStore.isColumnVisible(avId, colId);
}

// Watch for store changes to re-adjust DOM
watch(
  [globalShowPrimaryKey, effectiveShowEmptyAttributes, alignPropertiesLeft],
  () => {
    if (element.value) {
      AttributeViewService.adjustDOM(
        element.value,
        blockId,
        props.avData,
        globalShowPrimaryKey.value,
        effectiveShowEmptyAttributes.value,
        alignPropertiesLeft.value,
        props.onrefresh,
        isColumnVisible
      );
    }
  },
  { flush: "post" }
);

// Watch for avData changes to re-render (deep: true to catch in-place mutations)
watch(
  () => props.avData,
  () => {
    if (isInitialized && element.value) {
      logger.debug("avData changed, re-rendering native panel");
      renderProtyleAv();
    }
  },
  { deep: true }
);

onMounted(() => {
  logger.addBreadcrumb(blockId, "onMount");
  renderProtyleAv();
  setTimeout(() => {
    isInitialized = true;
  }, 100);
});

onUnmounted(() => {
  if (cleanupDataRenderingObserver) {
    cleanupDataRenderingObserver();
    cleanupDataRenderingObserver = null;
  }
});

function showContent(tabFocus: string) {
  if (!tabFocus) return;
  activateTab(tabFocus);
}

function activateTab(tabFocus: string) {
  logger.addBreadcrumb(blockId, "activateTab: " + LoggerService.getReadableName(tabFocus));
  const targetTab = element.value!.querySelectorAll(
    `[data-type="NodeAttributeView"][data-av-id="${tabFocus}"]`
  );
  const remainingTabs = element.value!.querySelectorAll(
    `[data-type="NodeAttributeView"]:not([data-av-id="${tabFocus}"])`
  );
  if (!targetTab.length) {
    logger.info("showContent: No target tab found");
    return;
  }
  settingsStore.activateTab(blockId, tabFocus);

  targetTab.forEach((item: Element) => {
    (item as HTMLElement).classList.remove("dpp-av-panel--hidden");
  });
  remainingTabs.forEach((item: Element) => {
    (item as HTMLElement).classList.add("dpp-av-panel--hidden");
  });
}

function renderProtyleAv() {
  if (cleanupDataRenderingObserver) {
    cleanupDataRenderingObserver();
    cleanupDataRenderingObserver = null;
  }

  protyle.renderAVAttribute(element.value, blockId, (renderedElement: HTMLElement) => {
    logger.debug("renderAVAttribute callback called");
    AttributeViewService.adjustDOM(
      renderedElement,
      blockId,
      props.avData,
      globalShowPrimaryKey.value,
      effectiveShowEmptyAttributes.value,
      alignPropertiesLeft.value,
      props.onrefresh,
      isColumnVisible
    );

    if (!settingsStore.isAnyTabActive(blockId)) {
      const first = renderedElement.querySelector(`[data-type="NodeAttributeView"]`);
      activateTab(first!.getAttribute("data-av-id")!);
    } else {
      activateTab(settingsStore.getActiveTab(blockId)!);
    }

    AttributeViewService.removeDataRenderingFromNodeAttributeViews(renderedElement);
    cleanupDataRenderingObserver = AttributeViewService.watchAndRemoveDataRendering(renderedElement);
  });
}
</script>

<template>
  <div>
    <LayoutTabBar
      v-if="tabs.length > 1"
      :tabs="tabs"
      :focus="currentSettings.lastSelectedAttributeView"
      @click="showContent"
    />
    <div ref="element" class="dpp-av-panel custom-attr dpp-av-panel--native" data-type="NodeBlockQueryEmbed"></div>
  </div>
</template>
