// src/components/CollapseButton.vue
<script setup lang="ts">
import { computed } from "vue";
import ActionButton from "@/components/ui/ActionButton.vue";
import { useLocalSettingStore } from "@/stores/localSettingStore";
import { useI18nStore } from "@/stores/i18nStore";
import type { SiYuanIcon } from "@/types/SiyuanIcon";

const props = defineProps<{
  documentId: string;
}>();

const settingsStore = useLocalSettingStore();
const i18nStore = useI18nStore();

const isCollapsed = computed(
  () => settingsStore.getDocumentSettings(props.documentId).isCollapsed,
);
const icon = computed<SiYuanIcon>(() => (isCollapsed.value ? "iconExpand" : "iconContract"));
const label = computed(() => (isCollapsed.value ? "" : i18nStore.strings.collapse));

function toggleCollapseTab() {
  settingsStore.toggleCollapsed(props.documentId);
}
</script>

<template>
  <ActionButton
    class="dpp-collapse-button"
    :icon="icon"
    :label="label"
    @click="toggleCollapseTab"
  />
</template>

// src/components/CollapseButton.svelte
<script lang="ts">
    import ActionButton from "@/components/ui/ActionButton.svelte";
    import {settingsStore} from "@/stores/localSettingStore";
    import {getContext} from "svelte";
    import {Context} from "@/types/context";
    import {i18nStore} from "@/stores/i18nStore";
    import type {SiYuanIcon} from "@/types/SiyuanIcon";

    interface Props {
        documentId?: string;
    }

    const {documentId: propDocumentId}: Props = $props();

    // Use prop if provided, otherwise fall back to context
    const contextDocumentId = getContext<string | undefined>(Context.BlockID);
    const documentId = $derived(propDocumentId || contextDocumentId);

    let isCollapsed = $derived($settingsStore.get(documentId).isCollapsed);
    let icon = $derived<SiYuanIcon>(isCollapsed ? "iconExpand" : "iconContract");
    let label = $derived(isCollapsed ? "" : $i18nStore.collapse);

    const toggleCollapseTab = () => {
        settingsStore.toggleCollapsed(documentId);
    };
</script>

<ActionButton
    class="dpp-collapse-button"
    {icon}
    {label}
    onclick={toggleCollapseTab}
/>
