// src/components/ShowEmptyAttributesToggle.vue
<script setup lang="ts">
import { computed } from "vue";
import ActionButton from "@/components/ui/ActionButton.vue";
import { useI18nStore } from "@/stores/i18nStore";
import { useConfigStore } from "@/stores/configStore";
import { useDocumentSettingsStore } from "@/stores/documentSettingsStore";

const props = defineProps<{
  documentId: string;
}>();

const i18nStore = useI18nStore();
const configStore = useConfigStore();
const documentSettingsStore = useDocumentSettingsStore();

const globalShowEmptyAttributes = computed(() => configStore.showEmptyAttributes);

const effectiveShowEmptyAttributes = computed(() =>
  documentSettingsStore.getEffectiveShowEmptyAttributes(
    props.documentId,
    globalShowEmptyAttributes.value
  )
);

function toggleShowEmptyAttributes(event: MouseEvent) {
  documentSettingsStore.toggleShowEmptyAttributes(
    props.documentId,
    globalShowEmptyAttributes.value
  );
  (event.currentTarget as HTMLButtonElement).blur();
}
</script>

<template>
  <ActionButton
    :icon="effectiveShowEmptyAttributes ? 'iconEyeoff' : 'iconEye'"
    :label="effectiveShowEmptyAttributes
      ? i18nStore.strings.hideEmptyAttributesToggle
      : i18nStore.strings.showEmptyAttributesToggle"
    class="dpp-empty-attributes-toggle"
    @click="toggleShowEmptyAttributes"
  />
</template>

// src/components/ShowEmptyAttributesToggle.svelte
<script lang="ts">
  import ActionButton from "@/components/ui/ActionButton.svelte";
  import { i18nStore } from "@/stores/i18nStore";
  import { configStore } from "@/stores/configStore";
  import { documentSettingsStore } from "@/stores/documentSettingsStore";

  interface Props {
    documentId: string;
  }

  const { documentId }: Props = $props();
  const i18n = $derived($i18nStore);

  // Global setting from plugin config
  const globalShowEmptyAttributes = $derived($configStore.showEmptyAttributes);

  // Per-document override
  const effectiveShowEmptyAttributesStore = $derived(
    documentSettingsStore.getEffectiveShowEmptyAttributes(
      documentId,
      globalShowEmptyAttributes
    )
  );
  const effectiveShowEmptyAttributes = $derived(
    $effectiveShowEmptyAttributesStore
  );

  function toggleShowEmptyAttributes(event: MouseEvent) {
    documentSettingsStore.toggleShowEmptyAttributes(
      documentId,
      globalShowEmptyAttributes
    );
    (event.currentTarget as HTMLButtonElement).blur();
  }
</script>

<ActionButton
  icon={effectiveShowEmptyAttributes ? "iconEyeoff" : "iconEye"}
  label={effectiveShowEmptyAttributes
    ? i18n.hideEmptyAttributesToggle
    : i18n.showEmptyAttributesToggle}
  onclick={toggleShowEmptyAttributes}
  class="dpp-empty-attributes-toggle"
/>
