// src/PluginPanel.vue
<script setup lang="ts">
import { ref, computed, provide, onMounted, onUnmounted } from "vue";
import AttributeViewPanel from "./components/AttributeViewPanel.vue";
import AttributeViewPanelNative from "./components/AttributeViewPanelNative.vue";
import ProtyleBreadcrumb from "@/components/ProtyleBreadcrumb.vue";
import Icon from "@/components/ui/Icon.vue";
import type { I18N } from "@/types/i18n";
import type { Protyle } from "siyuan";
import type { AttributeView } from "@/types/AttributeView";
import { ProtyleKey, BlockIDKey, RefreshCallbackKey } from "@/types/context";
import { useLocalSettingStore } from "@/stores/localSettingStore";
import { useConfigStore } from "@/stores/configStore";
import { Logger } from "@/services/LoggerService";
import { getAttributeViewKeys } from "@/api";

const props = withDefaults(
  defineProps<{
    i18n: I18N;
    allowEditing?: boolean;
    avData?: AttributeView[];
    protyle: Protyle;
    blockId: string;
  }>(),
  { allowEditing: false, avData: () => [] }
);

const settingsStore = useLocalSettingStore();
const configStore = useConfigStore();

// Mutable avData for refresh
const avData = ref<AttributeView[]>([...props.avData]);

// Debounce timer for data refresh
let refreshTimer: ReturnType<typeof setTimeout> | null = null;

function refreshAvData() {
  if (refreshTimer) clearTimeout(refreshTimer);
  refreshTimer = setTimeout(async () => {
    Logger.debug("Refreshing avData for blockId:", props.blockId);
    try {
      const newData = await getAttributeViewKeys(props.blockId);
      if (newData) avData.value = newData;
    } catch (error) {
      Logger.error("Failed to refresh avData", error);
    }
  }, 100);
}

// Provide context
provide(ProtyleKey, props.protyle);
provide(BlockIDKey, props.blockId);
provide(RefreshCallbackKey, refreshAvData);

const openAvPanel = (avId: string) => {
  settingsStore.activateTab(props.blockId, avId);
};

// Handle custom event from plugin when AV data changes via transaction
const handleAvDataChanged = (event: Event) => {
  const customEvent = event as CustomEvent<{ rowID: string; avID: string; keyID: string }>;
  // Only refresh if this event is for our block
  if (customEvent.detail.rowID === props.blockId) {
    Logger.debug("Received dpp-av-data-changed for our blockId, refreshing");
    refreshAvData();
  }
};

onMounted(() => {
  window.addEventListener("dpp-av-data-changed", handleAvDataChanged);
});

onUnmounted(() => {
  window.removeEventListener("dpp-av-data-changed", handleAvDataChanged);
  if (refreshTimer) clearTimeout(refreshTimer);
});

const isCollapsed = computed(() => settingsStore.getDocumentSettings(props.blockId).isCollapsed);
const showBottomSeparator = computed(() => configStore.showBottomSeparator);
</script>

<template>
  <div class="plugin-panel">
    <ProtyleBreadcrumb :single-tab="avData.length === 1">
      <span
        v-for="(av, i) in avData"
        :key="av.avID"
        class="protyle-breadcrumb__item"
        role="button"
        :tabindex="i"
        @click="openAvPanel(av.avID)"
        @keydown="openAvPanel(av.avID)"
      >
        <Icon icon="iconDatabase" />
        <span class="protyle-breadcrumb__text">{{ av.avName }}</span>
      </span>
    </ProtyleBreadcrumb>
    <template v-if="!isCollapsed">
      <AttributeViewPanelNative v-if="allowEditing" :av-data="avData" :onrefresh="refreshAvData" />
      <AttributeViewPanel v-else :av-data="avData" />
      <div v-if="showBottomSeparator" class="dpp-separator"></div>
    </template>
  </div>
</template>

<style scoped>
.dpp-separator {
  height: 0.0625em;
  background-color: var(--b3-theme-background-light);
  width: calc(100% - 1px);
  left: 0;
  top: 0.8125em;
}
</style>

// src/PluginPanel.svelte
<script lang="ts">
  import { setContext, untrack, onMount, onDestroy } from "svelte";
  import AttributeViewPanel from "./components/AttributeViewPanel.svelte";
  import { type I18N } from "@/types/i18n";
  import { Context } from "./types/context";
  import AttributeViewPanelNative from "./components/AttributeViewPanelNative.svelte";
  import type { Protyle } from "siyuan";
  import ProtyleBreadcrumb from "@/components/ProtyleBreadcrumb.svelte";
  import { type AttributeView } from "@/types/AttributeView";
  import Icon from "@/components/ui/Icon.svelte";
  import { settingsStore } from "@/stores/localSettingStore";
  import { Logger } from "@/services/LoggerService";
  import { getAttributeViewKeys } from "@/api";

  interface Props {
    i18n: I18N;
    allowEditing?: boolean;
    avData?: AttributeView[];
    protyle: Protyle;
    blockId: string;
  }

  let {
    i18n,
    allowEditing = false,
    avData: initialAvData = [],
    protyle,
    blockId,
  }: Props = $props();

  // Make avData mutable so we can refresh it
  // Use untrack to capture the initial value without subscribing to changes
  let avData = $state<AttributeView[]>([]);
  untrack(() => {
    avData = initialAvData;
  });

  // Debounce timer for data refresh
  let refreshTimer: ReturnType<typeof setTimeout> | null = null;

  // Feature flags controlled by localStorage
  // dpp-debug-native: Show the hidden native panel for debugging
  // dpp-use-native: Use only the native panel instead of custom panel
  const debugNativeEnabled = (typeof localStorage !== 'undefined' && localStorage.getItem('dpp-debug-native') === 'true');
  const useNativeOnly = (typeof localStorage !== 'undefined' && localStorage.getItem('dpp-use-native') === 'true');

  if (debugNativeEnabled) {
    Logger.debug('⚠️ Debug: Showing native panel');
  }
  if (useNativeOnly) {
    Logger.debug('⚠️ Using native-only rendering mode');
  }

  // Use untrack to explicitly capture initial values for context (these don't change after mount)
  untrack(() => {
    setContext(Context.I18N, i18n);
    setContext(Context.Protyle, protyle);
    setContext(Context.BlockID, blockId);
  });

  const openAvPanel = (avId: string) => {
    settingsStore.activateTab(blockId, avId);
  };

  /**
   * Refresh avData by re-fetching from the API.
   * Debounced to avoid excessive API calls when multiple mutations occur.
   */
  const refreshAvData = async () => {
    // Clear existing timer
    if (refreshTimer) {
      clearTimeout(refreshTimer);
    }

    // Debounce: wait 100ms after last change before refreshing
    refreshTimer = setTimeout(async () => {
      Logger.debug("Refreshing avData for blockId:", blockId);
      try {
        const newData = await getAttributeViewKeys(blockId);
        if (newData) {
          avData = newData;
        }
      } catch (error) {
        Logger.error("Failed to refresh avData", error);
      }
    }, 100);
  };

  /**
   * Handle custom event from plugin when AV data changes via transaction
   */
  const handleAvDataChanged = (event: CustomEvent<{ rowID: string; avID: string; keyID: string }>) => {
    // Only refresh if this event is for our block
    if (event.detail.rowID === blockId) {
      Logger.debug("Received dpp-av-data-changed for our blockId, refreshing");
      refreshAvData();
    }
  };

  onMount(() => {
    // Listen for AV data change events from the plugin
    window.addEventListener("dpp-av-data-changed", handleAvDataChanged as EventListener);
  });

  onDestroy(() => {
    // Clean up event listener
    window.removeEventListener("dpp-av-data-changed", handleAvDataChanged as EventListener);
    // Clear any pending refresh timer
    if (refreshTimer) {
      clearTimeout(refreshTimer);
    }
  });

  let isCollapsed = $derived($settingsStore.get(blockId).isCollapsed);

  // function onError(error: Error) {
  //     Sentry.withScope(scope => {
  //         scope.setTag('errorSource', PLUGIN_NAME);
  //         Sentry.captureException(error);
  //     });
  // }
</script>

<div class="plugin-panel">
  <ProtyleBreadcrumb singleTab={avData.length === 1}>
    {#each avData as av, i}
      <span
        class="protyle-breadcrumb__item"
        role="button"
        tabindex={i}
        onclick={() => {
          openAvPanel(av.avID);
        }}
        onkeydown={() => {
          openAvPanel(av.avID);
        }}
      >
        <Icon icon="iconDatabase" />
        <span class="protyle-breadcrumb__text">{av.avName}</span>
      </span>
    {/each}
  </ProtyleBreadcrumb>
  {#if !isCollapsed}
    {#if useNativeOnly}
      <!-- Native-only mode: use SiYuan's native rendering directly -->
      <AttributeViewPanelNative {avData} />
    {:else}
      <!-- Custom panel with hidden native for edit popup delegation -->
      <AttributeViewPanel {avData} {allowEditing} />
      <div class="dpp-native-debug" class:dpp-native-debug--visible={debugNativeEnabled}>
        <AttributeViewPanelNative {avData} />
      </div>
    {/if}
  {/if}
</div>

<style lang="css">
  .plugin-panel {
    /* Contain the absolutely positioned hidden native panel */
    position: relative;
    overflow: hidden;
  }

  .dpp-native-debug {
    /*
     * Visually hidden but still rendered for edit popup delegation.
     * This pattern ensures:
     * - No visual space taken
     * - No scrollbar effects
     * - Element is still in DOM so click events work
     */
    position: absolute !important;
    width: 1px !important;
    height: 1px !important;
    padding: 0 !important;
    margin: -1px !important;
    overflow: hidden !important;
    clip: rect(0, 0, 0, 0) !important;
    clip-path: inset(100%) !important;
    white-space: nowrap !important;
    border: 0 !important;
  }

  .dpp-native-debug--visible {
    /* When debug mode is enabled, show the panel normally */
    position: static !important;
    width: auto !important;
    height: auto !important;
    padding: 8px !important;
    margin: 8px 0 0 0 !important;
    overflow: visible !important;
    clip: auto !important;
    clip-path: none !important;
    white-space: normal !important;
    border: 2px dashed var(--b3-theme-error) !important;

    &::before {
      content: "Native Panel (Debug)";
      display: block;
      color: var(--b3-theme-error);
      font-weight: bold;
      margin-bottom: 8px;
    }
  }
</style>
