// src/components/ui/ActionButton.svelte
<script lang="ts">
    import Icon from "@/components/ui/Icon.svelte";
    import type {SiYuanIcon} from "@/types/SiyuanIcon";

    interface Props {
        label?: string | null;
        icon?: SiYuanIcon | null;
        class?: string | null;
        onclick?: (event: MouseEvent) => void;
    }

    let {
        label = null,
        icon = null,
        class: customClass = null,
        onclick = () => {},
    }: Props = $props();
</script>

<button
    class="b3-button b3-button--cancel {customClass ?? ''}"
    onclick={(event) => onclick(event)}
>
    {#if icon}
        <Icon {icon} />
    {/if}
    {#if label}
        {label}
    {/if}
</button>

// src/components/ui/ActionButton.vue
<script setup lang="ts">
import Icon from "@/components/ui/SiYuanIcon.vue";
import type { SiYuanIcon } from "@/types/SiyuanIcon";

const props = withDefaults(
  defineProps<{
    label?: string | null;
    icon?: SiYuanIcon | null;
    class?: string | null;
  }>(),
  {
    label: null,
    icon: null,
    class: null,
  },
);

const emit = defineEmits<{
  click: [event: MouseEvent];
}>();
</script>

<template>
  <button :class="['b3-button b3-button--cancel', props.class]" @click="emit('click', $event)">
    <Icon v-if="props.icon" :icon="props.icon" />
    <template v-if="props.label">{{ props.label }}</template>
  </button>
</template>
