// src/components/ui/Button.svelte
<script lang="ts">
    import {createEventDispatcher} from "svelte";
    import Icon from "@/components/ui/Icon.svelte";
    import type {SiYuanIcon} from "@/types/SiyuanIcon";

    export let label: string | null = null;
    export let icon: SiYuanIcon | null = null;
    export let isFocused: boolean = false;
    export let tooltip: string | null = null;

    const dispatch = createEventDispatcher();
</script>

<button
        class="block__icon block__icon--show"
        class:b3-tooltips__w={tooltip !== null}
        class:b3-tooltips={tooltip !== null}
        class:item--focus={isFocused}
        on:click={(event) => dispatch("click", { event })}
        on:keydown={(event) => dispatch("click", { event})}
        aria-label={tooltip}
>
    {#if icon}
        <Icon {icon}/>
    {/if}
    {#if label}
        <span class="item__text">{label}</span>
    {/if}
</button>

// src/components/ui/Button.vue
<script setup lang="ts">
import Icon from "@/components/ui/Icon.vue";
import type { SiYuanIcon } from "@/types/SiyuanIcon";

const props = withDefaults(
  defineProps<{
    label?: string | null;
    icon?: SiYuanIcon | null;
    isFocused?: boolean;
    tooltip?: string | null;
    class?: string | null;
  }>(),
  {
    label: null,
    icon: null,
    isFocused: false,
    tooltip: null,
    class: null,
  }
);

const emit = defineEmits<{
  click: [event: Event];
}>();

function handleClick(event: Event) {
  emit("click", event);
}
</script>

<template>
  <button
    :class="[
      'block__icon block__icon--show',
      props.class,
      {
        'b3-tooltips__w': props.tooltip !== null,
        'b3-tooltips': props.tooltip !== null,
        'item--focus': props.isFocused,
      },
    ]"
    :aria-label="props.tooltip"
    @click="handleClick"
    @keydown="handleClick"
  >
    <Icon v-if="props.icon" :icon="props.icon" />
    <span v-if="props.label" class="item__text">{{ props.label }}</span>
  </button>
</template>
